package jp.fuzzy31u.spring31.example.entity.dto;

public class BankAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.user_id
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.bank_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private Integer bankType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.bank_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.bank_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.branch_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String branchCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.branch_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String branchName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.account_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private Integer accountType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.account_number
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String accountNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank_account.account_holder
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	private String accountHolder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.user_id
	 * @return  the value of bank_account.user_id
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.user_id
	 * @param userId  the value for bank_account.user_id
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.bank_type
	 * @return  the value of bank_account.bank_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Integer getBankType() {
		return bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.bank_type
	 * @param bankType  the value for bank_account.bank_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setBankType(Integer bankType) {
		this.bankType = bankType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.bank_code
	 * @return  the value of bank_account.bank_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.bank_code
	 * @param bankCode  the value for bank_account.bank_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.bank_name
	 * @return  the value of bank_account.bank_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.bank_name
	 * @param bankName  the value for bank_account.bank_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.branch_code
	 * @return  the value of bank_account.branch_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getBranchCode() {
		return branchCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.branch_code
	 * @param branchCode  the value for bank_account.branch_code
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.branch_name
	 * @return  the value of bank_account.branch_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getBranchName() {
		return branchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.branch_name
	 * @param branchName  the value for bank_account.branch_name
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.account_type
	 * @return  the value of bank_account.account_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Integer getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.account_type
	 * @param accountType  the value for bank_account.account_type
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setAccountType(Integer accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.account_number
	 * @return  the value of bank_account.account_number
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getAccountNumber() {
		return accountNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.account_number
	 * @param accountNumber  the value for bank_account.account_number
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank_account.account_holder
	 * @return  the value of bank_account.account_holder
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getAccountHolder() {
		return accountHolder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank_account.account_holder
	 * @param accountHolder  the value for bank_account.account_holder
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setAccountHolder(String accountHolder) {
		this.accountHolder = accountHolder;
	}
}