package jp.fuzzy31u.spring31.example.entity.dto;

import java.util.ArrayList;
import java.util.List;

public class BankAccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected Integer offset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected Integer limit;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public BankAccountExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setOffset(Integer offset) {
		this.offset = offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Integer getOffset() {
		return offset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public Integer getLimit() {
		return limit;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andBankTypeIsNull() {
			addCriterion("bank_type is null");
			return (Criteria) this;
		}

		public Criteria andBankTypeIsNotNull() {
			addCriterion("bank_type is not null");
			return (Criteria) this;
		}

		public Criteria andBankTypeEqualTo(Integer value) {
			addCriterion("bank_type =", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeNotEqualTo(Integer value) {
			addCriterion("bank_type <>", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeGreaterThan(Integer value) {
			addCriterion("bank_type >", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("bank_type >=", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeLessThan(Integer value) {
			addCriterion("bank_type <", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeLessThanOrEqualTo(Integer value) {
			addCriterion("bank_type <=", value, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeIn(List<Integer> values) {
			addCriterion("bank_type in", values, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeNotIn(List<Integer> values) {
			addCriterion("bank_type not in", values, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeBetween(Integer value1, Integer value2) {
			addCriterion("bank_type between", value1, value2, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("bank_type not between", value1, value2, "bankType");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNull() {
			addCriterion("bank_code is null");
			return (Criteria) this;
		}

		public Criteria andBankCodeIsNotNull() {
			addCriterion("bank_code is not null");
			return (Criteria) this;
		}

		public Criteria andBankCodeEqualTo(String value) {
			addCriterion("bank_code =", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotEqualTo(String value) {
			addCriterion("bank_code <>", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThan(String value) {
			addCriterion("bank_code >", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeGreaterThanOrEqualTo(String value) {
			addCriterion("bank_code >=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThan(String value) {
			addCriterion("bank_code <", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLessThanOrEqualTo(String value) {
			addCriterion("bank_code <=", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeLike(String value) {
			addCriterion("bank_code like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotLike(String value) {
			addCriterion("bank_code not like", value, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeIn(List<String> values) {
			addCriterion("bank_code in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotIn(List<String> values) {
			addCriterion("bank_code not in", values, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeBetween(String value1, String value2) {
			addCriterion("bank_code between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankCodeNotBetween(String value1, String value2) {
			addCriterion("bank_code not between", value1, value2, "bankCode");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNull() {
			addCriterion("bank_name is null");
			return (Criteria) this;
		}

		public Criteria andBankNameIsNotNull() {
			addCriterion("bank_name is not null");
			return (Criteria) this;
		}

		public Criteria andBankNameEqualTo(String value) {
			addCriterion("bank_name =", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotEqualTo(String value) {
			addCriterion("bank_name <>", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThan(String value) {
			addCriterion("bank_name >", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameGreaterThanOrEqualTo(String value) {
			addCriterion("bank_name >=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThan(String value) {
			addCriterion("bank_name <", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLessThanOrEqualTo(String value) {
			addCriterion("bank_name <=", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameLike(String value) {
			addCriterion("bank_name like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotLike(String value) {
			addCriterion("bank_name not like", value, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameIn(List<String> values) {
			addCriterion("bank_name in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotIn(List<String> values) {
			addCriterion("bank_name not in", values, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameBetween(String value1, String value2) {
			addCriterion("bank_name between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBankNameNotBetween(String value1, String value2) {
			addCriterion("bank_name not between", value1, value2, "bankName");
			return (Criteria) this;
		}

		public Criteria andBranchCodeIsNull() {
			addCriterion("branch_code is null");
			return (Criteria) this;
		}

		public Criteria andBranchCodeIsNotNull() {
			addCriterion("branch_code is not null");
			return (Criteria) this;
		}

		public Criteria andBranchCodeEqualTo(String value) {
			addCriterion("branch_code =", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeNotEqualTo(String value) {
			addCriterion("branch_code <>", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeGreaterThan(String value) {
			addCriterion("branch_code >", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeGreaterThanOrEqualTo(String value) {
			addCriterion("branch_code >=", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeLessThan(String value) {
			addCriterion("branch_code <", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeLessThanOrEqualTo(String value) {
			addCriterion("branch_code <=", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeLike(String value) {
			addCriterion("branch_code like", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeNotLike(String value) {
			addCriterion("branch_code not like", value, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeIn(List<String> values) {
			addCriterion("branch_code in", values, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeNotIn(List<String> values) {
			addCriterion("branch_code not in", values, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeBetween(String value1, String value2) {
			addCriterion("branch_code between", value1, value2, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchCodeNotBetween(String value1, String value2) {
			addCriterion("branch_code not between", value1, value2, "branchCode");
			return (Criteria) this;
		}

		public Criteria andBranchNameIsNull() {
			addCriterion("branch_name is null");
			return (Criteria) this;
		}

		public Criteria andBranchNameIsNotNull() {
			addCriterion("branch_name is not null");
			return (Criteria) this;
		}

		public Criteria andBranchNameEqualTo(String value) {
			addCriterion("branch_name =", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameNotEqualTo(String value) {
			addCriterion("branch_name <>", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameGreaterThan(String value) {
			addCriterion("branch_name >", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameGreaterThanOrEqualTo(String value) {
			addCriterion("branch_name >=", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameLessThan(String value) {
			addCriterion("branch_name <", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameLessThanOrEqualTo(String value) {
			addCriterion("branch_name <=", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameLike(String value) {
			addCriterion("branch_name like", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameNotLike(String value) {
			addCriterion("branch_name not like", value, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameIn(List<String> values) {
			addCriterion("branch_name in", values, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameNotIn(List<String> values) {
			addCriterion("branch_name not in", values, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameBetween(String value1, String value2) {
			addCriterion("branch_name between", value1, value2, "branchName");
			return (Criteria) this;
		}

		public Criteria andBranchNameNotBetween(String value1, String value2) {
			addCriterion("branch_name not between", value1, value2, "branchName");
			return (Criteria) this;
		}

		public Criteria andAccountTypeIsNull() {
			addCriterion("account_type is null");
			return (Criteria) this;
		}

		public Criteria andAccountTypeIsNotNull() {
			addCriterion("account_type is not null");
			return (Criteria) this;
		}

		public Criteria andAccountTypeEqualTo(Integer value) {
			addCriterion("account_type =", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeNotEqualTo(Integer value) {
			addCriterion("account_type <>", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeGreaterThan(Integer value) {
			addCriterion("account_type >", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_type >=", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeLessThan(Integer value) {
			addCriterion("account_type <", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeLessThanOrEqualTo(Integer value) {
			addCriterion("account_type <=", value, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeIn(List<Integer> values) {
			addCriterion("account_type in", values, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeNotIn(List<Integer> values) {
			addCriterion("account_type not in", values, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeBetween(Integer value1, Integer value2) {
			addCriterion("account_type between", value1, value2, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("account_type not between", value1, value2, "accountType");
			return (Criteria) this;
		}

		public Criteria andAccountNumberIsNull() {
			addCriterion("account_number is null");
			return (Criteria) this;
		}

		public Criteria andAccountNumberIsNotNull() {
			addCriterion("account_number is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNumberEqualTo(String value) {
			addCriterion("account_number =", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberNotEqualTo(String value) {
			addCriterion("account_number <>", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberGreaterThan(String value) {
			addCriterion("account_number >", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberGreaterThanOrEqualTo(String value) {
			addCriterion("account_number >=", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberLessThan(String value) {
			addCriterion("account_number <", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberLessThanOrEqualTo(String value) {
			addCriterion("account_number <=", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberLike(String value) {
			addCriterion("account_number like", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberNotLike(String value) {
			addCriterion("account_number not like", value, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberIn(List<String> values) {
			addCriterion("account_number in", values, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberNotIn(List<String> values) {
			addCriterion("account_number not in", values, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberBetween(String value1, String value2) {
			addCriterion("account_number between", value1, value2, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountNumberNotBetween(String value1, String value2) {
			addCriterion("account_number not between", value1, value2, "accountNumber");
			return (Criteria) this;
		}

		public Criteria andAccountHolderIsNull() {
			addCriterion("account_holder is null");
			return (Criteria) this;
		}

		public Criteria andAccountHolderIsNotNull() {
			addCriterion("account_holder is not null");
			return (Criteria) this;
		}

		public Criteria andAccountHolderEqualTo(String value) {
			addCriterion("account_holder =", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderNotEqualTo(String value) {
			addCriterion("account_holder <>", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderGreaterThan(String value) {
			addCriterion("account_holder >", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderGreaterThanOrEqualTo(String value) {
			addCriterion("account_holder >=", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderLessThan(String value) {
			addCriterion("account_holder <", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderLessThanOrEqualTo(String value) {
			addCriterion("account_holder <=", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderLike(String value) {
			addCriterion("account_holder like", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderNotLike(String value) {
			addCriterion("account_holder not like", value, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderIn(List<String> values) {
			addCriterion("account_holder in", values, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderNotIn(List<String> values) {
			addCriterion("account_holder not in", values, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderBetween(String value1, String value2) {
			addCriterion("account_holder between", value1, value2, "accountHolder");
			return (Criteria) this;
		}

		public Criteria andAccountHolderNotBetween(String value1, String value2) {
			addCriterion("account_holder not between", value1, value2, "accountHolder");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bank_account
	 * @mbggenerated  Tue Sep 24 15:24:35 JST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bank_account
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 12 17:26:32 JST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}