package jp.fuzzy31u.spring31.example.entity.dao;

import java.util.List;

import jp.fuzzy31u.spring31.example.entity.dto.BankAccount;
import jp.fuzzy31u.spring31.example.entity.dto.BankAccountExample;

import org.apache.ibatis.annotations.Param;

public interface BankAccountDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int countByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int deleteByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int insert(BankAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int insertSelective(BankAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	List<BankAccount> selectByExample(BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int updateByExampleSelective(@Param("record") BankAccount record, @Param("example") BankAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank_account
	 * 
	 * @mbggenerated Tue Sep 24 15:24:35 JST 2013
	 */
	int updateByExample(@Param("record") BankAccount record, @Param("example") BankAccountExample example);
}